language: ruby
rvm:
 - 2.4
cache: bundler
before_install:
  - gem install bundler
  - gem install jekyll
gemfile: docs/Gemfile
script:
  - bundle exec jekyll algolia
  - bundle exec jekyll build && htmlproofer ./_site # https://jekyllrb.com/docs/continuous-integration/travis-ci/
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
